spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:where_are_we}?currentSchema=app
    username: ${POSTGRES_USER:dbuser}
    password: ${POSTGRES_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 5MB
server:
  port: 80
mybatis:
  type-handlers-package: com.sourcery.oirs.config.mybatis
  type-aliases-package: com.sourcery.oirs.config.mybatis
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    operations-sorter: method

