CREATE TABLE employee_table
(
        id int generated by default as identity,
        name varchar (50),
        position varchar (50),
        squad varchar (50),
        department varchar (50),
        address varchar (100)
);