ALTER TABLE employee_table
    ADD password  VARCHAR(255),
    ADD email     VARCHAR(255),
    ADD user_role VARCHAR(255) NOT NULL;

UPDATE employee_table
SET user_role = 'USER'
WHERE user_role IS NULL;

ALTER TABLE employee_table
    ADD CONSTRAINT user_role_constraint
        CHECK (user_role IN ('USER', 'ADMIN'));

ALTER TABLE employee_table
    DROP
        COLUMN address;

CREATE TABLE address
(
    id             int generated by default as identity,
    street_address varchar(255) NOT NULL,
    city           varchar(255) NOT NULL,
    state          varchar(255) NOT NULL,
    postcode       varchar(255) NOT NULL,
    country        varchar(255) NOT NULL,
    CONSTRAINT address_pk PRIMARY KEY (id)
);


ALTER TABLE employee_table
    ADD COLUMN address_id int;

ALTER TABLE employee_table
    ADD CONSTRAINT employee_address
        FOREIGN KEY (address_id)
            REFERENCES address (id)
            NOT DEFERRABLE
                INITIALLY IMMEDIATE
;


ALTER TABLE employee_table
    ADD CONSTRAINT user_pk PRIMARY KEY (id);

